# Generated by Django 2.0.5 on 2018-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=1000)),
                ('item_photo', models.CharField(max_length=1000)),
            ],
        ),
    ]
