# Generated by Django 2.0.5 on 2018-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='No Price Information', max_length=100),
            preserve_default=False,
        ),
    ]
